# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ae2c08ea2edab3c097d5c92e32f25b4b2f18a22653030d2f10f5c6c3394f03ac376e41f4511d4f3b933937446140c0544b1cd8fb301bd535f0178e1d5d18a763

test:
  secret_key_base: 722153adb524b3caaeeaf947d76012ea36d4e49c6361a25cf2d4bb760b183cf46ee98b39351f0824a9afe9c3f61982fc89af97ad2a3c85d0583b5fc8a5fceb76

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
